### ISSUE TITLE
Why not use count($this->LYRICS)-1

### ISSUE THREAD

**Issue by FeniX-MB** [RobDWaller/atlantic-city#4]
https://github.com/RobDWaller/atlantic-city/blob/a4cf321f78a4e700f9df3d23c704fd9722d0e1d1/src/AtlanticCity.php#L57

**Comment by FeniX-MB** [comment]
Why not use count($this->LYRICS)-1 instead of 34

**Comment by RobDWaller** [comment]
Possibly laziness, I might change that though. Thanks for the heads up. 👍

**Comment by RobDWaller** [comment]
Fixed in v0.3.0.
